### ISSUE TITLE
any updates for noetic?

### ISSUE THREAD

**Issue by fvillml** [udacity/RoboND-EKFLab#3]
As this is course material still being offered by udacity nowadays, I think it is very outdated. Are you planning to give noetic support so more people can follow it with more recent tools?

to be more specific, 
```shell
rosdep -i install turtlebot_gazebo
```

does not work for noetic. I am creating my own repository with necessary packages to make it work in noetic.  [link here](https://github.com/fvillml/turtlebot_sim_noetic). I have managed to compile it and run it but I cannot see the trajectories. I think it could be related to this [issue](https://github.com/udacity/odom_to_trajectory/issues/2).

**Comment by abhiojha8** [comment]
We haven't updated the content for ROS Noetic yet. We will notify if/when that's done. Thanks :)
